feat: order abbreviations by length
executablebooks/mystmd pull request #830
Opened 2024-01-08 16:23 UTC by agoose77

This might not be the right place, or the best way to do this, but this PR orders abbreviations defined in the frontmatter by length. As such, we no longer need to warn about the ordering.

2024-01-08 20:19 UTC, rowanc1 requested changes
This looks awesome, thanks @agoose77. 🚀

Can we move the sort code down a level so it is closer to where we do some other filtering? This should then be able to be shared a bit easily as the CLI code isn't going to be easy to share, e.g. with jupyterlab-myst and others.

Could you also run `npm run changeset` and write a short message that bumps the `myst-transform` and `myst-cli` packages (the myst-cli one will likely be manual once the changes are pushed down). This helps keep track of which packages need bumping.

2024-01-08 20:19 UTC, rowanc1 commented on packages/myst-cli/src/process/mdast.ts
> +  let abbreviations: Record<string, string> | undefined;
Can you move this code to here:

https://github.com/executablebooks/mystjs/blob/main/packages/myst-transforms/src/abbreviations.ts#L28

Maybe refactoring that to another function? e.g. `sortAndFilterAbbreviations` or something?

2024-01-08 20:20 UTC, rowanc1 commented on packages/myst-cli/src/process/mdast.ts
> +  let abbreviations: Record<string, string> | undefined;
There is going to be a bit of reprocessing/sorting every time this is run, but I think that is probably fine.

2024-01-09 14:25 UTC, agoose77 commented
@rowanc1 thanks! I realised that my understanding of what the transform did was not quite right; initially I thought it wasn't sensible to move the logic to myst-transforms.

As such, I've moved this to a simple in-line sort, making this PR very small!

2024-01-10 01:19 UTC, merged

2024-01-10 01:20 UTC, rowanc1 commented
Thanks again @agoose77, excited to see these sorts of quality-of-life changes come to life! :)